"""Accessibility smoke check (issue #52).

Asserts, against a real rendered page rather than generated Streamlit class
names, that the app's own controls:

- expose a meaningful accessible name (no icon-only control whose name is an
  unlabelled emoji glyph, and none with no name at all)
- have unique form labels in the Setup sidebar
- are reachable in a logical (top-to-bottom) keyboard order
- show a visible focus indicator when tabbed to
- fit within a narrow (~390x844) viewport without horizontal overflow in
  any of the app's scrolling panes

Scope is the app's *own* controls. Streamlit renders chrome of its own — the
sidebar expand/collapse buttons, the Deploy button, the main menu, dataframe
toolbars — whose names this repo cannot set from Python; those are excluded
by container and by Streamlit's ``kind`` attribute rather than by asserting
on generated class names.

The thumbs-up/down feedback buttons only render after a real scenario has
been generated by a live LLM call, which this network-free smoke check can't
do — their accessible name is covered instead by the unit-level
``test_thumbs_buttons_have_meaningful_accessible_names`` in
``tests/test_feedback.py``. The button sweep below still covers any
app-owned control that *is* reachable without generating a scenario, and
will automatically start covering the feedback buttons too if a future
change makes them reachable here.

Requires Playwright with its Chromium browser installed
(``pip install -r requirements-dev.txt && playwright install chromium``); it
skips itself otherwise; see ``tests/conftest.py``.
"""

from __future__ import annotations

import re

import pytest

pytestmark = pytest.mark.browser

_HAS_LETTER = re.compile(r"[^\W\d_]", re.UNICODE)

# The two containers Streamlit puts *app-authored* content into. Everything
# outside them (header, main menu, sidebar nav) is Streamlit's own chrome.
_APP_CONTAINERS = '[data-testid="stMain"], [data-testid="stSidebarUserContent"]'

# Streamlit tags its own chrome buttons with these `kind` values even when they
# render inside an app container (the dataframe toolbar is the common case).
_CHROME_KINDS = frozenset(
    {"header", "headerNoPadding", "elementToolbar", "borderlessIcon"}
)

# Reads the accessible name the same way a screen reader would reach it for
# these controls: an explicit aria-label wins, otherwise the visible text.
_APP_BUTTONS = """
({selector, chromeKinds}) => {
  const out = [];
  for (const container of document.querySelectorAll(selector)) {
    for (const el of container.querySelectorAll('button')) {
      if (chromeKinds.includes(el.getAttribute('kind') || '')) continue;
      if (el.closest('[data-testid="stElementToolbar"]')) continue;
      if (!el.offsetParent) continue;
      out.push((el.getAttribute('aria-label') || el.innerText || '').trim());
    }
  }
  return out;
}
"""

# A focus indicator is only "visible" if focusing actually changes something a
# sighted keyboard user can see. Streamlit draws it as a border-colour change
# on a wrapper around the focused input, not as an outline on the input
# itself, so compare the whole near-ancestor chain rather than one element.
_FOCUS_STYLES = """
(el) => {
  const of = node => {
    const s = getComputedStyle(node);
    return [s.outlineStyle, s.outlineWidth, s.outlineColor,
            s.boxShadow, s.borderColor, s.backgroundColor].join('|');
  };
  const chain = [];
  for (let n = el, i = 0; n && i < 5; n = n.parentElement, i++) chain.push(of(n));
  return chain;
}
"""


def _goto_scenario_page(page, base_url: str):
    """Open Threat Group Scenarios, which is where the app's own buttons live."""
    page.goto(f"{base_url}/Threat_Group_Scenarios", wait_until="networkidle")
    # The Enterprise bundle is ~53 MB and loads on first use, so the page's own
    # Generate button appearing is the signal that the first script run is done.
    # Waited for by test id, not by label, so a test asserting on that label
    # still fails on the label rather than timing out here.
    page.wait_for_selector('[data-testid="stButton"] button', timeout=120_000)


def test_app_buttons_all_have_a_meaningful_accessible_name(
    streamlit_server, page
) -> None:
    _goto_scenario_page(page, streamlit_server)

    names = page.evaluate(
        _APP_BUTTONS,
        {"selector": _APP_CONTAINERS, "chromeKinds": sorted(_CHROME_KINDS)},
    )
    assert names, "expected at least one app-owned button to sweep"

    violations = [n for n in names if not _HAS_LETTER.search(n)]
    assert violations == [], (
        f"app-owned buttons with no meaningful name: {violations!r} "
        f"(all names seen: {names!r})"
    )


def test_setup_sidebar_has_unique_non_empty_labels(streamlit_server, page) -> None:
    page.goto(streamlit_server, wait_until="networkidle")
    page.wait_for_selector('[data-testid="stSidebar"]')

    labels = page.eval_on_selector_all(
        '[data-testid="stSidebar"] [data-testid="stWidgetLabel"] p',
        "els => els.map(el => el.textContent.trim())",
    )

    assert labels, "expected at least one labelled Setup control"
    assert all(labels), "every Setup control must have non-empty label text"
    assert len(labels) == len(set(labels)), f"duplicate Setup labels: {labels}"


def test_setup_controls_are_tabbable_in_top_to_bottom_order(
    streamlit_server, page
) -> None:
    """Tabbing from the top of the page reaches Setup in the order it reads.

    Walks the real tab sequence instead of calling ``.focus()`` on a
    pre-collected list, so a control removed from the tab order (``tabindex=-1``,
    a wrapper that swallows focus) shows up as a missing stop rather than
    passing because the test focused it directly.
    """
    page.goto(streamlit_server, wait_until="networkidle")
    page.wait_for_selector('[data-testid="stSidebar"]')
    page.wait_for_selector('[data-testid="stSidebar"] [data-testid="stSelectbox"] input')

    expected = page.eval_on_selector_all(
        '[data-testid="stSidebar"] [data-testid="stWidgetLabel"] p',
        "els => els.map(el => el.textContent.trim())",
    )
    assert expected, "expected at least one labelled Setup control"

    stops = []
    page.evaluate("() => document.body.focus()")
    for _ in range(40):
        page.keyboard.press("Tab")
        stop = page.evaluate(
            """() => {
              const a = document.activeElement;
              if (!a || a === document.body) return null;
              const widget = a.closest('[data-testid="stSidebarUserContent"] '
                                       + '[data-testid="stWidgetLabel"], '
                                       + '[data-testid="stSidebarUserContent"] '
                                       + '[data-testid="stElementContainer"]');
              if (!widget) return {label: null};
              const label = widget.querySelector('[data-testid="stWidgetLabel"] p');
              return {label: label ? label.textContent.trim() : null};
            }"""
        )
        if stop and stop.get("label"):
            if not stops or stops[-1]["label"] != stop["label"]:
                stops.append(stop)
            if {s["label"] for s in stops} >= set(expected):
                break

    labelled = [s["label"] for s in stops]
    missing = [label for label in expected if label not in labelled]
    assert not missing, (
        f"Setup controls never reached by Tab: {missing} (reached: {labelled})"
    )

    order = [labelled.index(label) for label in expected]
    assert order == sorted(order), (
        f"Setup tab order does not match reading order: reached {labelled}, "
        f"laid out {expected}"
    )


def test_setup_controls_show_a_visible_focus_indicator(streamlit_server, page) -> None:
    """Focusing a Setup control must change something visible about it."""
    page.goto(streamlit_server, wait_until="networkidle")
    inputs = page.locator('[data-testid="stSidebar"] [data-testid="stSelectbox"] input')
    inputs.first.wait_for()
    assert inputs.count(), "expected at least one focusable Setup control"

    for i in range(inputs.count()):
        control = inputs.nth(i)
        page.evaluate("() => document.activeElement && document.activeElement.blur()")
        page.wait_for_timeout(150)
        before = control.evaluate(_FOCUS_STYLES)
        control.focus()
        page.wait_for_timeout(250)
        after = control.evaluate(_FOCUS_STYLES)
        assert before != after, (
            f"Setup control #{i} looks identical focused and unfocused "
            f"(styles: {before})"
        )


def test_no_horizontal_overflow_at_narrow_viewport(streamlit_server, page) -> None:
    page.set_viewport_size({"width": 390, "height": 844})
    _goto_scenario_page(page, streamlit_server)

    # `stAppViewContainer` sets `overflow-x: hidden`, so the document element
    # never reports a horizontal overflow no matter how wide the content gets —
    # asserting on `documentElement.scrollWidth` alone can never fail. The
    # scrolling actually happens on the panes inside it, so measure those.
    measure = """(ids) => {
      const out = [];
      for (const id of ids) {
        const el = document.querySelector(`[data-testid="${id}"]`);
        if (el) out.push({id, scrollWidth: el.scrollWidth,
                          clientWidth: el.clientWidth});
      }
      out.push({id: 'document',
                scrollWidth: document.documentElement.scrollWidth,
                clientWidth: document.documentElement.clientWidth});
      return out;
    }"""

    # At this width Streamlit collapses the sidebar, so Setup is reachable only
    # through the expand control — clicking a nav link directly would time out
    # against an off-viewport element rather than testing anything.
    expand = page.locator('button[data-testid="stExpandSidebarButton"]')
    assert expand.count(), "no control to expand the collapsed sidebar at 390px"
    expand.first.click()
    page.wait_for_selector('[data-testid="stSidebar"] [data-testid="stWidgetLabel"] p')
    page.wait_for_timeout(1000)  # let the expand animation settle before measuring
    labels = page.eval_on_selector_all(
        '[data-testid="stSidebar"] [data-testid="stWidgetLabel"] p',
        "els => els.map(el => el.textContent.trim())",
    )
    assert labels, "Setup is not reachable at 390x844"
    sidebar_panes = page.evaluate(measure, ["stSidebarContent"])

    # Back to the main pane: at this width the sidebar overlays it, so it has to
    # be dismissed before the Generate button can be scrolled to.
    page.keyboard.press("Escape")
    page.wait_for_timeout(1000)
    generate_button = page.get_by_role("button", name="Generate Scenario")
    generate_button.scroll_into_view_if_needed()
    assert generate_button.is_visible()
    main_panes = page.evaluate(measure, ["stMain", "stAppViewContainer"])

    panes = sidebar_panes + main_panes
    assert panes, "found no layout panes to measure"
    overflowing = [p for p in panes if p["scrollWidth"] > p["clientWidth"]]
    assert overflowing == [], (
        f"horizontal overflow at 390x844: {overflowing} (all panes: {panes})"
    )
