"""Accessibility smoke check (issue #52).

Asserts, against a real rendered page rather than generated Streamlit class
names, that the app's own controls:

- expose a meaningful accessible name (no icon-only control whose only name
  is an unlabelled emoji glyph)
- have unique form labels in the Setup sidebar
- are reachable in a logical (DOM/visual) keyboard order
- show a visible focus indicator when tabbed to
- fit within a narrow (~390x844) viewport without horizontal overflow

The thumbs-up/down feedback buttons only render after a real scenario has
been generated by a live LLM call, which this network-free smoke check can't
do — their accessible name is covered instead by the unit-level
``test_thumbs_buttons_have_meaningful_accessible_names`` in
``tests/test_feedback.py``. The button sweep below still covers any
icon-only control that *is* reachable without generating a scenario, and
will automatically start covering the feedback buttons too if a future
change makes them reachable here.

Requires Playwright with its Chromium browser installed
(``pip install -r requirements-dev.txt && playwright install chromium``); it
skips itself otherwise; see ``tests/conftest.py``.
"""

from __future__ import annotations

import re

import pytest

pytestmark = pytest.mark.browser

_HAS_LETTER = re.compile(r"[^\W\d_]", re.UNICODE)


def _accessible_name(button) -> str:
    aria_label = button.get_attribute("aria-label")
    if aria_label:
        return aria_label.strip()
    return button.inner_text().strip()


def test_no_icon_only_buttons_without_a_meaningful_name(streamlit_server, page) -> None:
    page.goto(streamlit_server, wait_until="networkidle")
    page.wait_for_selector('[data-testid="stSidebar"]')

    violations = []
    for button in page.get_by_role("button").all():
        name = _accessible_name(button)
        if name and not _HAS_LETTER.search(name):
            violations.append(name)

    assert violations == [], f"icon-only buttons with no meaningful name: {violations}"


def test_setup_sidebar_has_unique_non_empty_labels(streamlit_server, page) -> None:
    page.goto(streamlit_server, wait_until="networkidle")
    page.wait_for_selector('[data-testid="stSidebar"]')

    labels = page.eval_on_selector_all(
        '[data-testid="stSidebar"] [data-testid="stWidgetLabel"] p',
        "els => els.map(el => el.textContent.trim())",
    )

    assert labels, "expected at least one labelled Setup control"
    assert all(labels), "every Setup control must have non-empty label text"
    assert len(labels) == len(set(labels)), f"duplicate Setup labels: {labels}"


def test_setup_sidebar_tab_order_is_logical_with_visible_focus(streamlit_server, page) -> None:
    page.goto(streamlit_server, wait_until="networkidle")
    sidebar = page.locator('[data-testid="stSidebar"]')
    sidebar.wait_for()

    focusable = sidebar.locator(
        "button, input, textarea, [role='radio'], [role='combobox']"
    ).all()
    assert focusable, "expected at least one focusable Setup control"

    focusable[0].focus()
    for i, handle in enumerate(focusable):
        landed_correctly = handle.evaluate(
            "el => el === document.activeElement || el.contains(document.activeElement)"
        )
        assert landed_correctly, f"keyboard tab order skipped or reordered control #{i}"

        outline_style, box_shadow = handle.evaluate(
            "el => { const s = getComputedStyle(document.activeElement); "
            "return [s.outlineStyle, s.boxShadow]; }"
        )
        assert outline_style != "none" or box_shadow not in ("none", ""), (
            f"control #{i} has no visible focus indicator "
            f"(outline={outline_style!r}, box-shadow={box_shadow!r})"
        )

        if i + 1 < len(focusable):
            page.keyboard.press("Tab")


def test_no_horizontal_overflow_at_narrow_viewport(streamlit_server, page) -> None:
    page.set_viewport_size({"width": 390, "height": 844})
    page.goto(streamlit_server, wait_until="networkidle")
    page.get_by_role("link", name=re.compile("Threat Group Scenarios")).click()
    page.wait_for_load_state("networkidle")

    generate_button = page.get_by_role("button", name="Generate Scenario")
    generate_button.wait_for()
    assert generate_button.is_visible()

    scroll_width, client_width = page.evaluate(
        "() => [document.documentElement.scrollWidth, document.documentElement.clientWidth]"
    )
    assert scroll_width <= client_width, (
        f"document overflows horizontally at 390x844: scrollWidth={scroll_width} "
        f"> clientWidth={client_width}"
    )
